language: node_js # 构建所需的语言环境
node_js:
  - "v12.16.1" # 对应的版本
branches:
  only:
    - blog # 构建的分支
cache:
  directories:
    - node_modules # 依赖缓存的目录
before_install:
  - export TZ='Asia/Shanghai' # 设置时区
install:
  - yarn # 安装编译工具
script:
  - yarn run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # github 上的token环境变量
  # local-dir: ./_book/ ## 根据情况自定义到静态文件输出目录
  target_branch: master
  verbose: true
  on:
    branch: master
