language: node_js # 构建所需的语言环境
# os: windows
node_js:
  - "v12.16.1" # 对应的版本
branches:
  only:
    - blog # 构建的分支
cache:
  directories:
    - node_modules # 依赖缓存的目录
before_install:
  - export TZ='Asia/Shanghai' # 设置时区
install:
  - yarn add gitbook-cli
script:
  - yarn run build
# after_script:
#   - cd ./build
#   - git init
#   - git config user.name "${U_NAME}"
#   - git config user.email "${U_EMAIL}"
#   - git add .
#   - git commit -m "Update build"
#   - git push --force --quiet "https://${GITHUB_TOKEN}@${GH_REF}" master:master
# E: Build LifeCycle

deploy:
  provider: pages
  github_token: $GITHUB_TOKEN # github 上的token环境变量
  local_dir: ./_book/ ## 根据情况自定义到静态文件输出目录
  target-branch: master
  verbose: true
  on:
    branch: blog
