language: node_js # 构建所需的语言环境
# os: windows
node_js:
  - "v12.16.1" # 对应的版本
branches:
  only:
    - blog # 构建的分支
cache:
  directories:
    - node_modules # 依赖缓存的目录
before_install:
  - export TZ='Asia/Shanghai' # 设置时区
# install:
#   - yarn # 安装编译工具
script:
  - yarn run build
# after_script:
#   - cd ./build
#   - git init
#   - git config user.name "${U_NAME}"
#   - git config user.email "${U_EMAIL}"
#   - git add .
#   - git commit -m "Update build"
#   - git push --force --quiet "https://${GITHUB_TOKEN}@${GH_REF}" master:master
# E: Build LifeCycle

deploy:
  provider: pages
  skip_cleanup: true # 确保skip_cleanup设置为true，否则Travis CI将删除在构建过程中创建的所有文件，这可能会删除您尝试上传的文件。
  github_token: $GITHUB_TOKEN # github 上的token环境变量
  target_branch: master
  local_dir: "./build" # 上传的目录
  keep_history: true # 提交历史
  verbose: true
  on:
    branch: blog
